(define (problem two-cities)
  (:domain travel-strips)
  (:objects c1 c2 - city 
            h1 h2 - hotel)
  (:init (connected c1 c2)
         (not-started)
         (hotel-in h1 c1) (hotel-in h2 c2)
         (not-visited c1) (not-visited c2)
         (not-just-landed)
         (= (min-ciutats) 2))
  (:goal (<= (min-ciutats) 0))
)
