(define (problem petit1)
    (:requirements :strips :fluents)
    (:domain travel-strips)
    (:objects c1 c2 c3 c4 c5  - city
              h1 h2 h3 h4 h5 h6 h7 h8 h9 h10  - hotel)
    (:init  (connected c1 c2) (connected c1 c3) (connected c1 c5) 
            (connected c2 c5) (connected c3 c2) (connected c3 c4) 
            (connected c3 c5) (connected c4 c1) (connected c4 c2) 
            (connected c4 c5) (hotel-in h1 c1) (hotel-in h2 c1) (hotel-in h3 c2) 
            (hotel-in h4 c2) (hotel-in h5 c2) (hotel-in h6 c3) 
            (hotel-in h7 c3) (hotel-in h8 c3) (hotel-in h9 c4) 
            (hotel-in h10 c5) (not-visited c1) (not-visited c2) (not-visited c3) 
            (not-visited c4) (not-visited c5) (not-started) (not-just-landed) (= (min-ciutats) 4)

    )
    (:goal (<= (min-ciutats) 0))
)
