(define (problem test2)
    (:requirements :strips :fluents)
    (:domain travel-strips)
    (:objects c1 c2  - city
              h1 h2  - hotel)
    (:init  (connected c2 c1) (hotel-in h1 c1) (hotel-in h2 c2) (not-visited c1) (not-visited c2) (= (price c2 c1) 28) (= (price-hotel h1 c1) 28) (= (price-hotel h2 c2) 70) (not-started) (= (min-days) 1) (= (max-days) 1) (= (spent-days) 0) (= (min-days-viatge) 2) (= (cost-travel) 0)(= (min-cost-travel) 100) (= (max-cost-travel) 10000 )
    )
    (:goal (and (>= (cost-travel) (min-cost-travel)) (<= (min-days-viatge) 0)))
    (:metric minimize (cost-travel))
)
