(define (problem test1)
    (:requirements :strips :fluents)
    (:domain travel-strips)
    (:objects c1  - city
              h1  - hotel)
    (:init  (hotel-in h1 c1) (not-visited c1) (= (price-hotel h1 c1) 36) (not-started) (= (min-days) 1) (= (max-days) 1) (= (spent-days) 0) (= (min-days-viatge) 1) (= (cost-travel) 0)(= (min-cost-travel) 100) (= (max-cost-travel) 10000 )
    )
    (:goal (and (>= (cost-travel) (min-cost-travel)) (<= (min-days-viatge) 0)))
    (:metric minimize (cost-travel))
)
